version: 0.0
Resources:
  - ApiLambdaFunction:
      Type: AWS::Lambda::Function
      Properties:
        Name: cloudproof-api
        Alias: live
        CurrentVersion: <CURRENT_VERSION>
        TargetVersion: <TARGET_VERSION>
